local s = "Hello, World"
print(#s, s:upper(), s:lower(), s:sub(1, 5), s:sub(-5), s:sub(3, -3))
print(s:find("World"), s:find("o", 6), s:find("xyz"), s:find("l+"))
print(s:match("(%a+), (%a+)"))
print(s:gsub("o", "0"))
print(("abc"):rep(3, "-"), ("x"):byte(), string.char(72, 105))
for w in ("one two three"):gmatch("%a+") do io.write(w, ";") end print()
print(string.format("%d %5.2f %s %q %x %-5s| %05d", 42, 3.14159, "hi", "a\nb", 255, "ab", 7))
print(string.format("%g %g %g", 1e20, 0.1, 100))
print(tostring(10), tostring(1.5), tonumber("0x10"), tonumber("  12  "), tonumber("z", 36), tonumber("1e2"))
print(("key=val"):match("(%w+)=(%w+)"))
print(("  trim  "):match("^%s*(.-)%s*$") .. "|")
print(("hello world"):gsub("(%w+)", "<%1>"))
print(("abc"):gsub("", "-"))
print(("hello"):gsub("l", {l = "L"}))
print(("x = 1, y = 2"):gsub("(%w+) = (%w+)", function(k, v) return v .. "=" .. k end))
print(("%d"):format(3), #"\0ab", ("a\0b"):byte(2))
print(("test123"):find("%d+"), ("[x]"):find("[", 1, true))
print(("f(a(b)c)"):match("%b()"), ("THE (quick) fox"):find("%f[%a]%a+", 5))
print(string.reverse("abc"), ("abc"):len())
print(1 .. "", 1.0 .. "", -0.0 .. "", 2^63 .. "", math.maxinteger .. "")
print(10 // 3, 10.0 // 3, -7 // 2, -7 % 3, 7 % -3, 5.5 % 2, 3 / 2, 1 / 0, -1 / 0)
print(1 << 62, 1 << 63, 1 << 64, -1 >> 1, 5 & 3, 5 | 3, 5 ~ 3, ~0)
print(math.floor(3.7), math.ceil(3.2), math.abs(-4), math.max(1, 5, 3), math.min(2, 0.5))
print(math.huge, -math.huge, math.pi, math.sqrt(16), math.tointeger(3.0), math.type(1), math.type(1.0), math.type("1"))
print(string.format("%.3f", math.sin(1)), math.fmod(7, 3), math.modf(3.7))
print(8 // 0.0, -8 // 0.0, 0/0 ~= 0/0, math.ult(1, -1))
print("10" + 5, "3" * "4", 10 .. 20)
